const year = new Date().getFullYear();

export function landing() {
  return `<div class="app-shell">
    <header class="topbar"><div class="container" style="display:flex;align-items:center;justify-content:space-between;width:100%">
      <a class="brand" href="#"><span class="brand-mark">Y</span> YOLOTASK</a>
      <nav class="nav-links" aria-label="Main navigation"><a href="/about.html">About</a><a href="/how-it-works.html">How it works</a><a href="/campaigns.html">Campaigns</a><a href="/faq.html">FAQs</a></nav>
      <div class="nav-actions"><a class="btn btn-ghost" href="/auth/login.html">Log in</a><a class="btn btn-primary" href="/auth/register.html">Sign up</a></div>
    </div></header>
    <main>
      <section class="hero"><div class="hero-grid"></div><div class="container"><div class="hero-content">
        <span class="eyebrow">A trusted digital promotion marketplace</span>
        <h1>Put your attention to work.</h1>
        <p class="hero-copy">YOLOTASK connects ambitious earners with credible campaigns and gives advertisers a focused way to reach the right people.</p>
        <div class="hero-actions"><a class="btn btn-primary" href="/auth/register.html">Get started <span>↗</span></a><a class="btn btn-ghost" href="/auth/register.html">Advertise with us <span>↗</span></a></div>
        <p class="hero-note">Earner activation is ₦1,000. Advertisers register free and fund campaigns from wallet.</p>
      </div></div></section>
      <section class="stat-strip"><div class="container"><div class="stat-grid"><div class="stat"><strong>₦30–₦150</strong><span>Typical task rewards</span></div><div class="stat"><strong>2 roles</strong><span>Earners and advertisers</span></div><div class="stat"><strong>₦1,000</strong><span>One-time earner activation</span></div><div class="stat"><strong>Server-led</strong><span>Payments and wallet ledger</span></div></div></div></section>
      <section class="section" id="about"><div class="container"><div class="section-head"><div><div class="section-kicker">Why YOLOTASK</div><h2>Clarity creates confidence.</h2></div><p class="section-intro">Like the best Nigerian fintech experiences, YOLOTASK leads with transparency, simple steps, and a product people can understand before they sign up.</p></div><div class="feature-grid"><article class="card feature-card"><div class="icon-box">✓</div><h3>Verified activity</h3><p>Every task has a brief, a proof method, and a visible review path. No vague promises.</p></article><article class="card feature-card"><div class="icon-box">₦</div><h3>Clear economics</h3><p>Workers see payouts. Advertisers see campaign budget, fees, and the total wallet reservation.</p></article><article class="card feature-card"><div class="icon-box">◈</div><h3>Built for trust</h3><p>Role separation, server-side authorization, RLS, and an immutable ledger protect the platform.</p></article></div></div></section>
      <section class="section" id="how" style="background:#eef6f7"><div class="container split"><div class="split-visual"><div class="float-card"><strong>Campaign reach</strong><div style="display:flex;justify-content:space-between;margin-top:10px;font-size:.8rem"><span>2,480 eligible</span><span style="color:var(--teal-dark)">Targeted</span></div><div class="progress"><i style="width:82%"></i></div></div></div><div><div class="section-kicker">How it works</div><h2>A straightforward journey from interest to impact.</h2><div class="list" style="margin-top:23px"><div class="list-item"><span class="list-main"><span class="icon-box" style="margin:0;width:32px;height:32px">1</span><span><strong class="list-title">Create your profile</strong><span class="list-sub">Choose your role and interests.</span></span></span></div><div class="list-item"><span class="list-main"><span class="icon-box" style="margin:0;width:32px;height:32px">2</span><span><strong class="list-title">Choose your lane</strong><span class="list-sub">Activate as an earner or fund as an advertiser.</span></span></span></div><div class="list-item"><span class="list-main"><span class="icon-box" style="margin:0;width:32px;height:32px">3</span><span><strong class="list-title">Take meaningful action</strong><span class="list-sub">Complete tasks or publish a campaign.</span></span></span></div><div class="list-item"><span class="list-main"><span class="icon-box" style="margin:0;width:32px;height:32px">4</span><span><strong class="list-title">Track the outcome</strong><span class="list-sub">Follow reviews, balances, and campaign performance.</span></span></span></div></div></div></div></section>
      <section class="section" id="campaigns"><div class="container"><div class="section-head"><div><div class="section-kicker">Featured opportunities</div><h2>Campaigns with a clear next step.</h2></div><p class="section-intro">Advertisers create campaigns for focused audiences. Earners discover work that fits how they already spend time online.</p></div><div class="feature-grid"><article class="card feature-card"><span class="badge live">Community</span><h3 style="margin-top:18px">Join a founder community</h3><p>Connect with a Nigerian business community and submit screenshot proof.</p><strong class="amount gold">₦30 / worker</strong></article><article class="card feature-card"><span class="badge approved">Social engagement</span><h3 style="margin-top:18px">Discover a new creator</h3><p>Follow, engage, and share a creator brief with a targeted audience.</p><strong class="amount gold">₦80 / worker</strong></article><article class="card feature-card"><span class="badge pending">Website promotion</span><h3 style="margin-top:18px">Explore a digital product</h3><p>Visit a product page and share a concise proof of completion.</p><strong class="amount gold">₦100 / worker</strong></article></div></div></section>
      <section class="section" style="background:#fbfcfe"><div class="container"><div class="section-head"><div><div class="section-kicker">People first</div><h2>Built to feel dependable.</h2></div><p class="section-intro">A marketplace earns trust through the details: clear status, responsive support, and a record of what happened.</p></div><div class="feature-grid"><article class="card feature-card"><p>“The brief was clear, and I could see exactly when my proof moved to review.”</p><strong>— Adaeze, earner</strong></article><article class="card feature-card"><p>“Our campaign economics are easy to understand before we commit wallet balance.”</p><strong>— Tunde, advertiser</strong></article><article class="card feature-card"><p>“YOLOTASK gives digital promotion a process we can measure and improve.”</p><strong>— Chiamaka, growth lead</strong></article></div></div></section>
      <section class="section" id="faq"><div class="container split"><div><div class="section-kicker">FAQs</div><h2>Good questions deserve clear answers.</h2><p class="section-intro">Review the essentials before you create an account. The support centre is available once you are inside the platform.</p><a class="btn btn-secondary" href="/auth/register.html">Create an account ↗</a></div><div class="card panel"><details class="list-item" open><summary>What does an earner pay?</summary><p class="muted">Earners pay a one-time ₦1,000 activation fee. Earning features unlock only after Paystack verification.</p></details><details class="list-item"><summary>Can advertisers register for free?</summary><p class="muted">Yes. Advertisers register free and fund their wallet before creating a campaign.</p></details><details class="list-item"><summary>How does YOLOTASK protect balances?</summary><p class="muted">Money actions run through server-side authorization and database functions. The browser cannot set activation or wallet balances.</p></details><details class="list-item"><summary>How are audiences targeted?</summary><p class="muted">Advertisers can choose a general audience or target interests and gender without seeing private user records.</p></details></div></div></section>
      <section class="section" style="padding-top:20px"><div class="container"><div class="cta"><div class="section-kicker">Start with confidence</div><h2>Make your next move count.</h2><p style="color:#a5bad4;max-width:520px">Choose your role and join a platform designed around clear actions, accountable money flows, and measurable reach.</p><div class="hero-actions"><a class="btn btn-primary" href="/auth/register.html">Join YOLOTASK ↗</a><a class="btn btn-ghost" href="/auth/register.html">Launch a campaign ↗</a></div></div></div></section>
    </main>
    <footer class="footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="#" style="color:#fff"><span class="brand-mark">Y</span> YOLOTASK</a><p style="max-width:250px;font-size:.88rem">A Nifelux marketplace for the promotion economy.</p></div><div><h4>Platform</h4><a href="/about.html">About YOLOTASK</a><a href="/how-it-works.html">How it works</a><a href="/campaigns.html">Campaigns</a></div><div><h4>Trust</h4><a href="/faq.html">FAQs</a><a href="mailto:support@yolotask.example">Support</a><a href="#">Privacy</a></div><div><h4>Account</h4><a href="/auth/login.html">Log in</a><a href="/auth/register.html">Sign up</a></div></div><div class="footer-bottom"><span>© ${year} Nifelux. YOLOTASK.</span><span>Clear actions. Trusted outcomes.</span></div></div></footer>
  </div>`;
}
